baseURL = "https://g0246.github.io/"
languageCode = "en-us"
title = "Veutexus"
theme="archie"
copyright = "© G0246"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# disqusShortname = ""

paginate = 3 # articles per page

[params]
mode = "auto" # color-mode → light,dark,toggle or auto
useCDN = false # don't use CDNs for fonts and icons, instead serve them locally.
subtitle = "Welcome to my personal site! This is a website where you may learn about my journeys and other active projects. You can also see what I'm up to when I publish a new post."
mathjax = false # enable MathJax support
katex = true # enable KaTeX support
favicon = "/icons/favicon.png"

[markup.goldmark.renderer]
unsafe = true

[Taxonomies]
tags = "tags"

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/G0246"

# [[params.social]]
# name = "Twitter"
# icon = "twitter"
# url = ""

[[params.social]]
name = "GitLab"
icon = "gitlab"
url = "https://gitlab.com/G0246/"

# Main menu items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4